# apiVersion: configsync.gke.io/v1beta1
# kind: RootSync
# metadata:
#   name: gateway-root
#   namespace: config-management-system
# spec:
#   sourceType: git
#   sourceFormat: unstructured
#   git:
#     repo: https://github.com/kkr16/gke-enterprise-demo.git
#     branch: main
#     dir: config/gateway/root
#     auth: none
#     period: 30s
