kind: Gateway
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: mc-gateway
  namespace: mc-gateway
spec:
  gatewayClassName: gke-l7-global-external-managed-mc
  addresses:
  - type: NamedAddress
    value: mcg-global-ip    
  listeners:
  - name: https
    protocol: HTTPS
    port: 443
    tls:
      mode: Terminate
      options:
        networking.gke.io/pre-shared-certs: bookinfo-cert
    allowedRoutes:
      kinds:
      - kind: HTTPRoute
      namespaces:
        from: Selector
        selector:
          matchLabels:
            shared-gateway-access: "true"

  # - name: http
  #   protocol: HTTP
  #   port: 80
  #   allowedRoutes:
  #     kinds:
  #     - kind: HTTPRoute
  #     namespaces:
  #       from: Selector
  #       selector:
  #         matchLabels:
  #           shared-gateway-access: "true"
